pytest:
  markers:
    - test_1
    - test_2
    - test_3
    - test_4
    - test_5
  verbosity: "-ra -q"
  report: true
  browser: "chrome"

email:
  sender: "${EMAIL_SENDER}"
  password: "${EMAIL_PASSWORD}"
  recipients:
    - "qa1@example.com"
    - "qa2@example.com"
    - "qa3@example.com"
